on:
  repository_dispatch:
    types: [ incident_report ]


jobs:
  handle_incident:
    runs-on: ubuntu-latest
    steps:
      -  name: print incident details
         run: echo "Incident Report"


#curl -X POST \
#-H "Authorization: token $GITHUB_PAT" \
#-H "Accept: application/vnd.github.v3+json" \
#https://api.github.com/repos/ahmedel-tawil/ghactions/dispatches \
#-d '{"event_type": "incident_report"}'